name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: install LCUI
      run: |
        wget https://github.com/lc-soft/LCUI/archive/develop.zip -O LCUI-develop.zip
        unzip LCUI-develop.zip
        rm LCUI-develop.zip
        cd LCUI-develop
        sh ./autogen.sh
        ./configure
        make
        sudo make install
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup
      run: |
        npm install
        npm link
        tradc --version
    - name: Run test
      run: |
        tradc example/src/app.jsx
        mkdir exmaple/build
        cd exmaple/build
        cmake ../
        make
      env:
        CI: true
